apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-aws-infra
  annotations:
    github.com/project-slug: DinuRajDeva/backstage-aws-infra
    aws.amazon.com/amazon-ecr-arn: arn:aws:ecr:ap-south-1:923801260899:repository/backstage-test-12345
    backstage.io/managed-by-origin-location: url:https://github.com/DinuRajDeva/backstage-aws-infra/blob/main/catalog-info.yaml
spec:
  type: other
  lifecycle: unknown
  owner: guests
